#!/usr/bin/env php
<?php
// 命令行入口文件

namespace Think;

// 检测PHP环境
if (version_compare(PHP_VERSION, '7.0.0', '<')) {
    die('require PHP > 7.0.0 !');
}

// 定义应用目录
define('APP_PATH', __DIR__ . '/App/');

// 定义缓存目录
define('RUNTIME_PATH', __DIR__ . '/Runtime/');

define('APP_MODE', 'cli');

// 开启调试模式 建议开发阶段开启 部署阶段注释或者设为false
define('APP_DEBUG', false);

// 加载基础文件
require __DIR__ . '/Core/Base.php';

App::init();

// 控制台初始化
Console::init();