<?php


use Phinx\Migration\AbstractMigration;

class FillDefaultApiAuthNodeData extends AbstractMigration
{
    /**
     * Change Method.
     *
     * Write your reversible migrations using this method.
     *
     * More information on writing migrations is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-abstractmigration-class
     *
     * The following commands can be used in this method and Phinx will
     * automatically reverse them when rolling back:
     *
     *    createTable
     *    renameTable
     *    addColumn
     *    renameColumn
     *    addIndex
     *    addForeignKey
     *
     * Remember to call "create()" or "update()" and NOT "save()" when working
     * with the Table class.
     */

    /**
     * Migrate Up.
     */
    public function up()
    {
        // 初始化table
        $table = $this->table('strack_auth_node');
        $rows = [
            [
                'name' => '动作单条查找',
                'code' => 'action_find',
                'lang' => 'Action_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Action/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '动作多条查找',
                'code' => 'action_select',
                'lang' => 'Action_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Action/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '动作修改',
                'code' => 'action_update',
                'lang' => 'Action_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Action/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '动作创建',
                'code' => 'action_create',
                'lang' => 'Action_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Action/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '动作删除',
                'code' => 'action_delete',
                'lang' => 'Action_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Action/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '动作字段',
                'code' => 'action_fields',
                'lang' => 'Action_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Action/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '日历设置单条查找',
                'code' => 'calendar_find',
                'lang' => 'Calendar_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Calendar/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '日历设置多条查找',
                'code' => 'calendar_select',
                'lang' => 'Calendar_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Calendar/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '日历设置修改',
                'code' => 'calendar_update',
                'lang' => 'Calendar_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Calendar/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '日历设置创建',
                'code' => 'calendar_create',
                'lang' => 'Calendar_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Calendar/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '日历设置删除',
                'code' => 'calendar_delete',
                'lang' => 'Calendar_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Calendar/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '日历设置字段',
                'code' => 'calendar_fields',
                'lang' => 'Calendar_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Calendar/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '部门单条查找',
                'code' => 'department_find',
                'lang' => 'Department_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Department/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '部门多条查找',
                'code' => 'department_select',
                'lang' => 'Department_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Department/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '部门修改',
                'code' => 'department_update',
                'lang' => 'Department_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Department/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '部门创建',
                'code' => 'department_create',
                'lang' => 'Department_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Department/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '部门删除',
                'code' => 'department_delete',
                'lang' => 'Department_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Department/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '部门字段',
                'code' => 'department_fields',
                'lang' => 'Department_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Department/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '目录模板单条查找',
                'code' => 'dirtemplate_find',
                'lang' => 'DirTemplate_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/DirTemplate/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '目录模板多条查找',
                'code' => 'dirtemplate_select',
                'lang' => 'DirTemplate_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/DirTemplate/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '目录模板修改',
                'code' => 'dirtemplate_update',
                'lang' => 'DirTemplate_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/DirTemplate/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '目录模板创建',
                'code' => 'dirtemplate_create',
                'lang' => 'DirTemplate_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/DirTemplate/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '目录模板删除',
                'code' => 'dirtemplate_delete',
                'lang' => 'DirTemplate_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/DirTemplate/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '目录模板字段',
                'code' => 'dirtemplate_fields',
                'lang' => 'DirTemplate_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/DirTemplate/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '目录变量单条查找',
                'code' => 'dirvariable_find',
                'lang' => 'DirVariable_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/DirVariable/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '目录变量多条查找',
                'code' => 'dirvariable_select',
                'lang' => 'DirVariable_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/DirVariable/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '目录变量修改',
                'code' => 'dirvariable_update',
                'lang' => 'DirVariable_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/DirVariable/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '目录变量创建',
                'code' => 'dirvariable_create',
                'lang' => 'DirVariable_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/DirVariable/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '目录变量删除',
                'code' => 'dirvariable_delete',
                'lang' => 'DirVariable_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/DirVariable/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '目录变量字段',
                'code' => 'dirvariable_fields',
                'lang' => 'DirVariable_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/DirVariable/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '磁盘单条查找',
                'code' => 'disk_find',
                'lang' => 'Disk_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Disk/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '磁盘多条查找',
                'code' => 'disk_select',
                'lang' => 'Disk_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Disk/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '磁盘修改',
                'code' => 'disk_update',
                'lang' => 'Disk_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Disk/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '磁盘创建',
                'code' => 'disk_create',
                'lang' => 'Disk_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Disk/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '磁盘删除',
                'code' => 'disk_delete',
                'lang' => 'Disk_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Disk/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '磁盘字段',
                'code' => 'disk_fields',
                'lang' => 'Disk_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Disk/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '实体单条查找',
                'code' => 'entity_find',
                'lang' => 'Entity_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Entity/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '实体多条查找',
                'code' => 'entity_select',
                'lang' => 'Entity_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Entity/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '实体修改',
                'code' => 'entity_update',
                'lang' => 'Entity_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Entity/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '实体创建',
                'code' => 'entity_create',
                'lang' => 'Entity_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Entity/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '实体删除',
                'code' => 'entity_delete',
                'lang' => 'Entity_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Entity/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '实体字段',
                'code' => 'entity_fields',
                'lang' => 'Entity_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Entity/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '文件单条查找',
                'code' => 'file_find',
                'lang' => 'File_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/File/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '文件多条查找',
                'code' => 'file_select',
                'lang' => 'File_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/File/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '文件修改',
                'code' => 'file_update',
                'lang' => 'File_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/File/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '文件创建',
                'code' => 'file_create',
                'lang' => 'File_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/File/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '文件删除',
                'code' => 'file_delete',
                'lang' => 'File_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/File/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '文件字段',
                'code' => 'file_fields',
                'lang' => 'File_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/File/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '关注单条查找',
                'code' => 'follow_find',
                'lang' => 'Follow_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Follow/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '关注多条查找',
                'code' => 'follow_select',
                'lang' => 'Follow_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Follow/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '关注修改',
                'code' => 'follow_update',
                'lang' => 'Follow_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Follow/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '关注创建',
                'code' => 'follow_create',
                'lang' => 'Follow_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Follow/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '关注删除',
                'code' => 'follow_delete',
                'lang' => 'Follow_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Follow/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '关注字段',
                'code' => 'follow_fields',
                'lang' => 'Follow_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Follow/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '水平关联配置单条查找',
                'code' => 'horizontalconfig_find',
                'lang' => 'HorizontalConfig_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/HorizontalConfig/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '水平关联配置多条查找',
                'code' => 'horizontalconfig_select',
                'lang' => 'HorizontalConfig_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/HorizontalConfig/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '水平关联配置修改',
                'code' => 'horizontalconfig_update',
                'lang' => 'HorizontalConfig_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/HorizontalConfig/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '水平关联配置创建',
                'code' => 'horizontalconfig_create',
                'lang' => 'HorizontalConfig_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/HorizontalConfig/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '水平关联配置删除',
                'code' => 'horizontalconfig_delete',
                'lang' => 'HorizontalConfig_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/HorizontalConfig/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '水平关联配置字段',
                'code' => 'horizontalconfig_fields',
                'lang' => 'HorizontalConfig_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/HorizontalConfig/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '水平关联单条查找',
                'code' => 'horizontal_find',
                'lang' => 'Horizontal_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Horizontal/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '水平关联多条查找',
                'code' => 'horizontal_select',
                'lang' => 'Horizontal_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Horizontal/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '水平关联修改',
                'code' => 'horizontal_update',
                'lang' => 'Horizontal_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Horizontal/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '水平关联创建',
                'code' => 'horizontal_create',
                'lang' => 'Horizontal_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Horizontal/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '水平关联删除',
                'code' => 'horizontal_delete',
                'lang' => 'Horizontal_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Horizontal/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '水平关联字段',
                'code' => 'horizontal_fields',
                'lang' => 'Horizontal_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Horizontal/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '媒体单条查找',
                'code' => 'media_find',
                'lang' => 'Media_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Media/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '媒体多条查找',
                'code' => 'media_select',
                'lang' => 'Media_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Media/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '媒体修改',
                'code' => 'media_update',
                'lang' => 'Media_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Media/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '媒体创建',
                'code' => 'media_create',
                'lang' => 'Media_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Media/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '媒体删除',
                'code' => 'media_delete',
                'lang' => 'Media_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Media/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '媒体字段',
                'code' => 'media_fields',
                'lang' => 'Media_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Media/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '成员单条查找',
                'code' => 'member_find',
                'lang' => 'Member_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Member/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '成员多条查找',
                'code' => 'member_select',
                'lang' => 'Member_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Member/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '成员修改',
                'code' => 'member_update',
                'lang' => 'Member_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Member/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '成员创建',
                'code' => 'member_create',
                'lang' => 'Member_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Member/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '成员删除',
                'code' => 'member_delete',
                'lang' => 'Member_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Member/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '成员字段',
                'code' => 'member_fields',
                'lang' => 'Member_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Member/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '反馈单条查找',
                'code' => 'note_find',
                'lang' => 'Note_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Note/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '反馈多条查找',
                'code' => 'note_select',
                'lang' => 'Note_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Note/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '反馈修改',
                'code' => 'note_update',
                'lang' => 'Note_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Note/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '反馈创建',
                'code' => 'note_create',
                'lang' => 'Note_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Note/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '反馈删除',
                'code' => 'note_delete',
                'lang' => 'Note_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Note/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '反馈字段',
                'code' => 'note_fields',
                'lang' => 'Note_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Note/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '现场数据单条查找',
                'code' => 'onset_find',
                'lang' => 'Onset_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Onset/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '现场数据多条查找',
                'code' => 'onset_select',
                'lang' => 'Onset_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Onset/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '现场数据修改',
                'code' => 'onset_update',
                'lang' => 'Onset_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Onset/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '现场数据创建',
                'code' => 'onset_create',
                'lang' => 'Onset_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Onset/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '现场数据删除',
                'code' => 'onset_delete',
                'lang' => 'Onset_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Onset/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '现场数据字段',
                'code' => 'onset_fields',
                'lang' => 'Onset_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Onset/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '项目磁盘单条查找',
                'code' => 'projectdisk_find',
                'lang' => 'ProjectDisk_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/ProjectDisk/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '项目磁盘多条查找',
                'code' => 'projectdisk_select',
                'lang' => 'ProjectDisk_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/ProjectDisk/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '项目磁盘修改',
                'code' => 'projectdisk_update',
                'lang' => 'ProjectDisk_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/ProjectDisk/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '项目磁盘创建',
                'code' => 'projectdisk_create',
                'lang' => 'ProjectDisk_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/ProjectDisk/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '项目磁盘删除',
                'code' => 'projectdisk_delete',
                'lang' => 'ProjectDisk_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/ProjectDisk/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '项目磁盘字段',
                'code' => 'projectdisk_fields',
                'lang' => 'ProjectDisk_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/ProjectDisk/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '项目成员单条查找',
                'code' => 'projectmember_find',
                'lang' => 'ProjectMember_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/ProjectMember/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '项目成员多条查找',
                'code' => 'projectmember_select',
                'lang' => 'ProjectMember_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/ProjectMember/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '项目成员修改',
                'code' => 'projectmember_update',
                'lang' => 'ProjectMember_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/ProjectMember/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '项目成员创建',
                'code' => 'projectmember_create',
                'lang' => 'ProjectMember_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/ProjectMember/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '项目成员删除',
                'code' => 'projectmember_delete',
                'lang' => 'ProjectMember_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/ProjectMember/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '项目成员字段',
                'code' => 'projectmember_fields',
                'lang' => 'ProjectMember_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/ProjectMember/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '项目单条查找',
                'code' => 'project_find',
                'lang' => 'Project_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Project/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '项目多条查找',
                'code' => 'project_select',
                'lang' => 'Project_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Project/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '项目修改',
                'code' => 'project_update',
                'lang' => 'Project_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Project/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '项目创建',
                'code' => 'project_create',
                'lang' => 'Project_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Project/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '项目删除',
                'code' => 'project_delete',
                'lang' => 'Project_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Project/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '项目字段',
                'code' => 'project_fields',
                'lang' => 'Project_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Project/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '项目模板单条查找',
                'code' => 'projecttemplate_find',
                'lang' => 'ProjectTemplate_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/ProjectTemplate/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '项目模板多条查找',
                'code' => 'projecttemplate_select',
                'lang' => 'ProjectTemplate_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/ProjectTemplate/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '项目模板修改',
                'code' => 'projecttemplate_update',
                'lang' => 'ProjectTemplate_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/ProjectTemplate/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '项目模板创建',
                'code' => 'projecttemplate_create',
                'lang' => 'ProjectTemplate_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/ProjectTemplate/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '项目模板删除',
                'code' => 'projecttemplate_delete',
                'lang' => 'ProjectTemplate_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/ProjectTemplate/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '项目模板字段',
                'code' => 'projecttemplate_fields',
                'lang' => 'ProjectTemplate_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/ProjectTemplate/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '状态单条查找',
                'code' => 'status_find',
                'lang' => 'Status_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Status/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '状态多条查找',
                'code' => 'status_select',
                'lang' => 'Status_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Status/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '状态修改',
                'code' => 'status_update',
                'lang' => 'Status_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Status/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '状态创建',
                'code' => 'status_create',
                'lang' => 'Status_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Status/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '状态删除',
                'code' => 'status_delete',
                'lang' => 'Status_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Status/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '状态字段',
                'code' => 'status_fields',
                'lang' => 'Status_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Status/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '工序单条查找',
                'code' => 'step_find',
                'lang' => 'Step_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Step/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '工序多条查找',
                'code' => 'step_select',
                'lang' => 'Step_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Step/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '工序修改',
                'code' => 'step_update',
                'lang' => 'Step_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Step/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '工序创建',
                'code' => 'step_create',
                'lang' => 'Step_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Step/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '工序删除',
                'code' => 'step_delete',
                'lang' => 'Step_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Step/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '工序字段',
                'code' => 'step_fields',
                'lang' => 'Step_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Step/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '标签关联单条查找',
                'code' => 'taglink_find',
                'lang' => 'TagLink_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/TagLink/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '标签关联多条查找',
                'code' => 'taglink_select',
                'lang' => 'TagLink_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/TagLink/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '标签关联修改',
                'code' => 'taglink_update',
                'lang' => 'TagLink_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/TagLink/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '标签关联创建',
                'code' => 'taglink_create',
                'lang' => 'TagLink_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/TagLink/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '标签关联删除',
                'code' => 'taglink_delete',
                'lang' => 'TagLink_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/TagLink/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '标签关联字段',
                'code' => 'taglink_fields',
                'lang' => 'TagLink_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/TagLink/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '标签单条查找',
                'code' => 'tag_find',
                'lang' => 'Tag_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Tag/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '标签多条查找',
                'code' => 'tag_select',
                'lang' => 'Tag_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Tag/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '标签修改',
                'code' => 'tag_update',
                'lang' => 'Tag_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Tag/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '标签创建',
                'code' => 'tag_create',
                'lang' => 'Tag_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Tag/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '标签删除',
                'code' => 'tag_delete',
                'lang' => 'Tag_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Tag/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '标签字段',
                'code' => 'tag_fields',
                'lang' => 'Tag_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Tag/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '时间日志注意事项单条查找',
                'code' => 'timelogissue_find',
                'lang' => 'TimelogIssue_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/TimelogIssue/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '时间日志注意事项多条查找',
                'code' => 'timelogissue_select',
                'lang' => 'TimelogIssue_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/TimelogIssue/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '时间日志注意事项修改',
                'code' => 'timelogissue_update',
                'lang' => 'TimelogIssue_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/TimelogIssue/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '时间日志注意事项创建',
                'code' => 'timelogissue_create',
                'lang' => 'TimelogIssue_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/TimelogIssue/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '时间日志注意事项删除',
                'code' => 'timelogissue_delete',
                'lang' => 'TimelogIssue_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/TimelogIssue/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '时间日志注意事项字段',
                'code' => 'timelogissue_fields',
                'lang' => 'TimelogIssue_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/TimelogIssue/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '时间日志单条查找',
                'code' => 'timelog_find',
                'lang' => 'Timelog_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Timelog/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '时间日志多条查找',
                'code' => 'timelog_select',
                'lang' => 'Timelog_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Timelog/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '时间日志修改',
                'code' => 'timelog_update',
                'lang' => 'Timelog_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Timelog/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '时间日志创建',
                'code' => 'timelog_create',
                'lang' => 'Timelog_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Timelog/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '时间日志删除',
                'code' => 'timelog_delete',
                'lang' => 'Timelog_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Timelog/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '时间日志字段',
                'code' => 'timelog_fields',
                'lang' => 'Timelog_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Timelog/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '用户配置单条查找',
                'code' => 'userconfig_find',
                'lang' => 'UserConfig_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/UserConfig/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '用户配置多条查找',
                'code' => 'userconfig_select',
                'lang' => 'UserConfig_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/UserConfig/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '用户配置修改',
                'code' => 'userconfig_update',
                'lang' => 'UserConfig_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/UserConfig/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '用户配置创建',
                'code' => 'userconfig_create',
                'lang' => 'UserConfig_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/UserConfig/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '用户配置删除',
                'code' => 'userconfig_delete',
                'lang' => 'UserConfig_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/UserConfig/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '用户配置字段',
                'code' => 'userconfig_fields',
                'lang' => 'UserConfig_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/UserConfig/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '自定义字段单条查找',
                'code' => 'variable_find',
                'lang' => 'Variable_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Variable/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '自定义字段多条查找',
                'code' => 'variable_select',
                'lang' => 'Variable_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Variable/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '自定义字段修改',
                'code' => 'variable_update',
                'lang' => 'Variable_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Variable/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '自定义字段创建',
                'code' => 'variable_create',
                'lang' => 'Variable_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Variable/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '自定义字段删除',
                'code' => 'variable_delete',
                'lang' => 'Variable_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Variable/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '自定义字段字段',
                'code' => 'variable_fields',
                'lang' => 'Variable_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Variable/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '自定义字段值单条查找',
                'code' => 'variablevalue_find',
                'lang' => 'VariableValue_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/VariableValue/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '自定义字段值多条查找',
                'code' => 'variablevalue_select',
                'lang' => 'VariableValue_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/VariableValue/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '自定义字段值修改',
                'code' => 'variablevalue_update',
                'lang' => 'VariableValue_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/VariableValue/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '自定义字段值创建',
                'code' => 'variablevalue_create',
                'lang' => 'VariableValue_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/VariableValue/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '自定义字段值删除',
                'code' => 'variablevalue_delete',
                'lang' => 'VariableValue_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/VariableValue/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '自定义字段值字段',
                'code' => 'variablevalue_fields',
                'lang' => 'VariableValue_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/VariableValue/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '用户单条查找',
                'code' => 'user_find',
                'lang' => 'User_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/User/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '用户多条查找',
                'code' => 'user_select',
                'lang' => 'User_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/User/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '用户修改',
                'code' => 'user_update',
                'lang' => 'User_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/User/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '用户创建',
                'code' => 'user_create',
                'lang' => 'User_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/User/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '用户删除',
                'code' => 'user_delete',
                'lang' => 'User_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/User/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '用户字段',
                'code' => 'user_fields',
                'lang' => 'User_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/User/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '提交文件单条查找',
                'code' => 'filecommit_find',
                'lang' => 'FileCommit_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/FileCommit/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '提交文件多条查找',
                'code' => 'filecommit_select',
                'lang' => 'FileCommit_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/FileCommit/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '提交文件修改',
                'code' => 'filecommit_update',
                'lang' => 'FileCommit_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/FileCommit/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '提交文件创建',
                'code' => 'filecommit_create',
                'lang' => 'FileCommit_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/FileCommit/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '提交文件删除',
                'code' => 'filecommit_delete',
                'lang' => 'FileCommit_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/FileCommit/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '提交文件字段',
                'code' => 'filecommit_fields',
                'lang' => 'FileCommit_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/FileCommit/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '文件类型单条查找',
                'code' => 'filetype_find',
                'lang' => 'FileType_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/FileType/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '文件类型多条查找',
                'code' => 'filetype_select',
                'lang' => 'FileType_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/FileType/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '文件类型修改',
                'code' => 'filetype_update',
                'lang' => 'FileType_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/FileType/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '文件类型创建',
                'code' => 'filetype_create',
                'lang' => 'FileType_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/FileType/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '文件类型删除',
                'code' => 'filetype_delete',
                'lang' => 'FileType_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/FileType/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '文件类型字段',
                'code' => 'filetype_fields',
                'lang' => 'FileType_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/FileType/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '任务单条查找',
                'code' => 'task_find',
                'lang' => 'Task_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Task/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '任务多条查找',
                'code' => 'task_select',
                'lang' => 'Task_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Task/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '任务修改',
                'code' => 'task_update',
                'lang' => 'Task_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Task/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '任务创建',
                'code' => 'task_create',
                'lang' => 'Task_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Task/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '任务删除',
                'code' => 'task_delete',
                'lang' => 'Task_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Task/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '任务字段',
                'code' => 'task_fields',
                'lang' => 'Task_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/Task/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '通用动作单条查找',
                'code' => 'common_action_find',
                'lang' => 'Common_Action_Find',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/CommonAction/find',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '通用动作多条查找',
                'code' => 'common_action_select',
                'lang' => 'Common_Action_Select',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/CommonAction/select',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '通用动作修改',
                'code' => 'common_action_update',
                'lang' => 'Common_Action_Update',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/CommonAction/update',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '通用动作创建',
                'code' => 'common_action_create',
                'lang' => 'Common_Action_Create',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/CommonAction/create',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '通用动作删除',
                'code' => 'common_action_delete',
                'lang' => 'Common_Action_Delete',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/CommonAction/delete',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '通用动作字段',
                'code' => 'common_action_fields',
                'lang' => 'Common_Action_Fields',
                'type' => 'route',
                'module' => 'api',
                'project_id' => '0',
                'module_id' => '0',
                'rules' => 'api/CommonAction/fields',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '用户成员信息',
                'code' => 'get_member_data',
                'lang' => 'Get_Member_Data',
                'type' => 'route',
                'module' => 'api',
                'module_id' => '0',
                'project_id' => '0',
                'rules' => 'api/User/getMemberData',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '模板路径',
                'code' => 'get_template_path',
                'lang' => 'Get_Template_Path',
                'type' => 'route',
                'module' => 'api',
                'module_id' => '0',
                'project_id' => '0',
                'rules' => 'api/DirTemplate/getTemplatePath',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string,
            ],
            [
                'name' => '项目路径',
                'code' => 'get_item_path',
                'lang' => 'Get_Item_Path',
                'type' => 'route',
                'module' => 'api',
                'module_id' => '0',
                'project_id' => '0',
                'rules' => 'api/DirTemplate/getItemPath',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '创建数据结构',
                'code' => 'create_schema',
                'lang' => 'Create_Schema',
                'type' => 'route',
                'module' => 'api',
                'module_id' => '0',
                'project_id' => '0',
                'rules' => 'api/Schema/createSchema',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '获取数据结构',
                'code' => 'get_schema',
                'lang' => 'Get_Schema',
                'type' => 'route',
                'module' => 'api',
                'module_id' => '0',
                'project_id' => '0',
                'rules' => 'api/Schema/getSchema',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '更新数据结构',
                'code' => 'update_schema',
                'lang' => 'Update_Schema',
                'type' => 'route',
                'module' => 'api',
                'module_id' => '0',
                'project_id' => '0',
                'rules' => 'api/Schema/updateSchema',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '指定的媒体服务器',
                'code' => 'get_media_server_item',
                'lang' => 'Get_Media_Server_Item',
                'type' => 'route',
                'module' => 'api',
                'module_id' => '0',
                'project_id' => '0',
                'rules' => 'api/Media/getMediaServerItem',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '获取媒体指定上传服务器配置信息',
                'code' => 'get_media_upload_server',
                'lang' => 'Get_Media_Upload_Server',
                'type' => 'route',
                'module' => 'api',
                'module_id' => '0',
                'project_id' => '0',
                'rules' => 'api/Media/getMediaUploadServer',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '获取所有媒体服务器状态',
                'code' => 'get_media_server_status',
                'lang' => 'Get_Media_Server_Status',
                'type' => 'route',
                'module' => 'api',
                'module_id' => '0',
                'project_id' => '0',
                'rules' => 'api/Media/getMediaServerStatus',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '创建媒体',
                'code' => 'create_media',
                'lang' => 'Create_Media',
                'type' => 'route',
                'module' => 'api',
                'module_id' => '0',
                'project_id' => '0',
                'rules' => 'api/Media/createMedia',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '更新媒体',
                'code' => 'update_media',
                'lang' => 'Update_Media',
                'type' => 'route',
                'module' => 'api',
                'module_id' => '0',
                'project_id' => '0',
                'rules' => 'api/Media/updateMedia',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '查找媒体',
                'code' => 'get_media',
                'lang' => 'Get_Media',
                'type' => 'route',
                'module' => 'api',
                'module_id' => '0',
                'project_id' => '0',
                'rules' => 'api/Media/getMediaData',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '获取指定尺寸的缩率图路径',
                'code' => 'get_specify_size_thumb_path',
                'lang' => 'Get_Specify_Size_Thumb_Path',
                'type' => 'route',
                'module' => 'api',
                'module_id' => '0',
                'project_id' => '0',
                'rules' => 'api/Media/getSpecifySizeThumbPath',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '多媒体信息获取',
                'code' => 'select_media_data',
                'lang' => 'Select_Media_Data',
                'type' => 'route',
                'module' => 'api',
                'module_id' => '0',
                'project_id' => '0',
                'rules' => 'api/Media/selectMediaData',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '水平关联创建',
                'code' => 'create_horizontal',
                'lang' => 'Create_Horizontal',
                'type' => 'route',
                'module' => 'api',
                'module_id' => '0',
                'project_id' => '0',
                'rules' => 'api/Horizontal/createHorizontal',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '指定选项配置获取',
                'code' => 'get_options',
                'lang' => 'Get_Options',
                'type' => 'route',
                'module' => 'api',
                'module_id' => '0',
                'project_id' => '0',
                'rules' => 'api/Options/getOptions',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '指定选项配置更新',
                'code' => 'update_options',
                'lang' => 'Update_Options',
                'type' => 'route',
                'module' => 'api',
                'module_id' => '0',
                'project_id' => '0',
                'rules' => 'api/Options/updateOptions',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '指定选项配置添加',
                'code' => 'add_options',
                'lang' => 'Add_Options',
                'type' => 'route',
                'module' => 'api',
                'module_id' => '0',
                'project_id' => '0',
                'rules' => 'api/Options/addOptions',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '开启计时器',
                'code' => 'start_timer',
                'lang' => 'Start_Timer',
                'type' => 'route',
                'module' => 'api',
                'module_id' => '0',
                'project_id' => '0',
                'rules' => 'api/Timelog/startTimer',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '停止计时器',
                'code' => 'stop_timer',
                'lang' => 'Stop_Timer',
                'type' => 'route',
                'module' => 'api',
                'module_id' => '0',
                'project_id' => '0',
                'rules' => 'api/Timelog/stopTimer',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '默认视图创建',
                'code' => 'create_default_view',
                'lang' => 'Create_Default_View',
                'type' => 'route',
                'module' => 'api',
                'module_id' => '0',
                'project_id' => '0',
                'rules' => 'api/View/createDefaultView',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],

            [
                'name' => '模块获取',
                'code' => 'get_module_data',
                'lang' => 'Get_Module_Data',
                'type' => 'route',
                'module' => 'api',
                'module_id' => '0',
                'project_id' => '0',
                'rules' => 'api/Module/getModuleData',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '获取websocket服务器',
                'code' => 'get_web_socket_server',
                'lang' => 'Get_Web_Socket_Server',
                'type' => 'route',
                'module' => 'api',
                'module_id' => '0',
                'project_id' => '0',
                'rules' => 'api/Options/getWebSocketServer',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '获取Email服务器',
                'code' => 'get_email_server',
                'lang' => 'Get_Email_Server',
                'type' => 'route',
                'module' => 'api',
                'module_id' => '0',
                'project_id' => '0',
                'rules' => 'api/Options/getEmailServer',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ],
            [
                'name' => '获取log服务器',
                'code' => 'get_event_log_server',
                'lang' => 'Get_Event_Log_Server',
                'type' => 'route',
                'module' => 'api',
                'module_id' => '0',
                'project_id' => '0',
                'rules' => 'api/Options/getEventLogServer',
                'uuid' => Webpatser\Uuid\Uuid::generate()->string
            ]
        ];
        $table->insert($rows)->save();
    }

    /**
     * Migrate Down.
     */
    public function down()
    {
        $this->execute('DELETE FROM strack_auth_node');
    }
}
